dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from df_goods.search_views import MySearchView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('df_goods.urls')),
    url(r'^user/', include('df_user.urls')),
    url(r'^cart/', include('df_cart.urls')),
    url(r'^order/', include('df_order.urls')),
    url(r'^search/', MySearchView()),
]

df_cart/urls.py
from django.conf.urls import url
from df_cart import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^add/$', views.add),
    url(r'^count/$', views.count1),
    url(r'^edit/$', views.edit),
    url(r'^remove/$', views.remove),
]

df_user/urls.py
from django.conf.urls import url
from df_user import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^check_register/$', views.check_register),
    url(r'^user_check/$', views.user_check),
    url(r'^login/$', views.login, name='login'),
    url(r'^login_check/$', views.login_check),
    url(r'^info/$', views.info, name='info'),
    url(r'^center/$',views.center, name='center'),
    url(r'^user_site/$', views.site, name='site'),
    url(r'^shou_save/$', views.shou_save),
    url('^logout$',views.logout,name='logout'),
]

df_order/models.py
from django.db import models

# Create your models here.
from django.db import models


# Create your models here.
class OrderInfo(models.Model):
    oid = models.CharField(max_length=20, primary_key=True)  # 订单编号 主键
    user = models.ForeignKey('df_user.UserInfo',on_delete=models.CASCADE)  # 所属用户
    odate = models.DateTimeField(auto_now_add=True)  # 订单时间
    oIsPay = models.BooleanField(default=0)  # 订单支付状态
    ototal = models.DecimalField(max_digits=6, decimal_places=2)  # 金额
    oaddr = models.CharField(max_length=150)


class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('df_goods.GoodsInfo',on_delete=models.CASCADE)  # 订单详情 订单商品
    order = models.ForeignKey(OrderInfo,on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    count = models.IntegerField()

df_user/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    objects = None
    uname = models.CharField(max_length=20)
    upwd = models.CharField(max_length=40)
    uemail = models.CharField(max_length=30)
    isValid = models.BooleanField(default=True)
    isActive = models.BooleanField(default=False)


class UserAddressInfo(models.Model):
    uname = models.CharField(max_length=20)
    uaddress = models.CharField(max_length=100)
    uphone = models.CharField(max_length=11)
    user = models.ForeignKey('UserInfo',on_delete=models.CASCADE)

df_user/forms.py
from django import forms
from df_user.models import UserInfo
from django.core.exceptions import ValidationError

class UserForm(forms.ModelForm):
    repwd = forms.CharField(max_length=40, widget=forms.PasswordInput(attrs={'id': 'cpwd'}))
    class Meta:
        model = UserInfo
        fields = ['uname', 'upwd', 'uemail']

    uname = forms.CharField(widget=forms.TextInput(attrs={'id': 'user_name'}))
    upwd = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'pwd'}))
    uemail = forms.CharField(widget=forms.EmailInput(attrs={'id': 'email'}))
    def clean(self):
        if self.cleaned_data.get('upwd') != self.cleaned_data.get('repwd'):
            self.add_error("repwd", ValidationError("两次密码不一样"))
        else:
            return self.cleaned_data

df_user/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404

from df_order.models import OrderInfo
from df_user.forms import UserForm
from hashlib import sha1
from df_user.models import UserInfo, UserAddressInfo
from django.http import JsonResponse, HttpResponseRedirect
from df_goods.models import *


def is_login(func):
    # 判断是否登录状态的装饰器
    def inner(request, *args, **kwargs):
        if request.session.get('user_id'):
            # 如果用户已登录
            return func(request, *args, **kwargs)
        else:
            # 如果没有登录 重定向到登录页面
            if request.is_ajax():
                return JsonResponse({'isLogin': 0})
            return redirect('login')

    return inner


# Create your views here.
def register(request):
    form = UserForm()
    return render(request, 'df_user/register.html', {'form': form})


def check_register(request):
    dict1 = request.POST
    upwd = dict1.get('upwd')
    form = UserForm(request.POST)

    if form.is_valid():
        user = form.save(commit=False)
        s1 = sha1()
        s1.update(upwd.encode())
        upwd = s1.hexdigest()  # 获取到加密后的密码
        user.upwd = upwd
        user.save()  # 注册成功
        return redirect('login')
    return render(request, 'df_user/register.html', {'form': form})


def user_check(request):
    uname = request.GET.get('uname')
    xxx = UserInfo.objects.filter(uname=uname).count()  # 根据用户名查找用户 个数
    return JsonResponse({'num': xxx})


def login(request):
    uname = request.COOKIES.get('uname')
    return render(request, 'df_user/login.html', {'title': '登录', 'error_name': 0, 'error_pwd': 0, 'uname': uname})


def login_check(request):
    dict1 = request.POST
    uname = dict1.get('username')
    upwd = dict1.get('pwd')
    jizhu = dict1.get('jizhu', 0)
    users = UserInfo.objects.filter(uname=uname)  # 根据用户名查找用户
    if users:
        s1 = sha1()
        s1.update(upwd.encode())
        if s1.hexdigest() == users[0].upwd:
            # 登录成功
            res = redirect('info')  # 跳转到用户中心
            if jizhu:
                # 如果点了记住用户名
                res.set_cookie('uname', uname)
            else:
                res.set_cookie('uname', uname, max_age=-1)  # 到浏览器关闭
            request.session['user_id'] = users[0].id
            request.session['user_name'] = uname
            return res
        else:
            # 密码不对
            context = {'title': '登录', 'error_name': 0, 'error_pwd': 1, 'uname': uname}
            return render(request, 'df_user/login.html', context)
    else:
        # 没有找到用户
        context = {'title': '登录', 'error_name': 1, 'error_pwd': 0, 'uname': uname}
        return render(request, 'df_user/login.html', context)


@is_login
def info(request):
    id = request.session.get('user_id')
    user = UserInfo.objects.get(id=id)
    user_addr = UserAddressInfo.objects.filter(user=user)
    if  user_addr:
        user_addr=user_addr[0]
    # user_addr = get_object_or_404(UserAddressInfo, user_id=user.id)

    # 最近浏览
    jin = request.COOKIES.get('jin', '[]')
    jin_list = eval(jin)
    # [30, 29, 10]
    goods = [GoodsInfo.objects.get(pk=id) for id in jin_list]

    return render(request, 'df_user/user_center_info.html', {'title': '用户中心', 'goods': goods, 'user_addr': user_addr})


@is_login
def site(request):
    id = request.session.get('user_id')
    print('--------------------------------')
    print(id)
    user = UserInfo.objects.get(id=id)
    user_addr = user.useraddressinfo_set.all()
    str1 = ''
    if user_addr:
        user_addr = user_addr[0]
        print(user_addr)
        str1 = f'{user_addr.uaddress},({user_addr.uname})收,电话:{user_addr.uphone}'
    return render(request, 'df_user/user_center_site.html', {'str1': str1})

@is_login
def center(request):
    id = request.session.get('user_id')  #当前用户
    myorders = OrderInfo.objects.filter(user_id=id)

    p = Paginator(myorders, 10)  # 一页多少个
    page_num = request.GET.get('page', 1)
    now_page = int(page_num)  # 当前页
    page = p.page(now_page)  # 获取当前页
    page_range = list(range(max(now_page - 2, 1), now_page)) + list(range(now_page, min(p.num_pages, now_page + 2) + 1))
    # 当页码间隔大于2时 显示省略号
    if page_range[0] - 1 > 2:
        page_range.insert(0, '...')
    if p.num_pages - page_range[-1] > 2:
        page_range.append('...')
    # 显示第一页和最后一页
    if page_range[0] != 1:
        page_range.insert(0, 1)
    if page_range[-1] != p.num_pages:
        page_range.append(p.num_pages)

    content = {'page': page, 'page_range': page_range, 'title': '全部订单'}

    # return render(request,'user/user_center_order.html',{'title':'全部订单','myorders':myorders})

    return render(request, 'df_user/user_center_order.html', content)

def shou_save(request):
    dict1 = request.POST
    ushou = dict1.get('shou')
    uaddr = dict1.get('addr')
    ucode = dict1.get('ucode')
    uphone = dict1.get('uphone')
    id = request.session.get('user_id')
    user = UserInfo.objects.get(id=id)
    u_addr = UserAddressInfo()
    u_addr.uname = ushou
    u_addr.uaddress = uaddr
    u_addr.uphone = uphone
    u_addr.user = user
    u_addr.save()
    return redirect('site')

def logout(request):
    request.session.flush() #清空seeion缓存
    return HttpResponseRedirect('/user/login')

templates/df_user/login.html
{% extends 'base1.html' %}
{% block head %}
    <script>
        $(function () {
            if({{ error_name }}==1){
            $('.user_error').html('用户名错误').show();
            }
            if ({{ error_pwd }}==1){
                $('.pwd_error').html('密码错误').show();
            }
        })
    </script>
{% endblock %}
{% block body %}


    <div class="login_top clearfix">
        <a href="/" class="login_logo"><img src="/static/images/logo02.png"></a>
    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="login_banner fl"></div>
            <div class="slogan fl">日夜兼程 · 急速送达</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>用户登录</h1>
                    <a href="{% url 'register' %}">立即注册</a>
                </div>
                <div class="form_input">
                    <form action="/user/login_check/" method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                        <div class="user_error">输入错误</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                        <div class="pwd_error">输入错误</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="jizhu" value="1" checked="checked">
                            <label>记住用户名</label>
                            <a href="#">忘记密码</a>
                        </div>
                        <input type="submit" name="" value="登录" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/df_user/register.html
{% extends 'base1.html' %}
{% block head %}
    <script src="/static/js/register.js"></script>
{% endblock %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <a class="reg_logo"><img src="/static/images/logo02.png"></a>
            <div class="reg_slogan">足不出户 · 新鲜每一天</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户注册</h1>
                <a href="{% url 'login' %}">登录</a>
            </div>
            <div class="reg_form clearfix">
                <form id="reg_form" method="post" action="/user/check_register/">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            {% comment %} <input type="text" name="user_name" id="user_name">
                            <span class="error_tip">提示信息</span>{% endcomment %}
                            {{ form.uname }}
                            <span class="error_tip">{{ form.uname.errors }}</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            {% comment %}                     <input type="password" name="pwd" id="pwd">
                            <span class="error_tip">提示信息</span>{% endcomment %}
                            {{ form.upwd }}
                            <span class="error_tip"> {{ form.upwd.errors }}</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            {% comment %}             <input type="password" name="cpwd" id="cpwd">
                            <span class="error_tip">提示信息</span>{% endcomment %}
                            {{ form.repwd }}
                            <span>{{ form.repwd.errors }}</span>
                        </li>
                        <li>
                            <label>邮箱:</label>
                            {% comment %}                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>{% endcomment %}
                            {{ form.uemail }}
                            <span class="error_tip">
                                {{ form.uemail.errors }}
                            </span>
                        </li>
                        <li class="agreement">
                            <input type="checkbox" name="allow" id="allow" checked="checked">
                            <label>同意”天天生鲜用户使用协议“</label>
                            <span class="error_tip2">提示信息</span>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="注 册" name="">
                        </li>
                    </ul>
                </form>
            </div>

        </div>

    </div>

{% endblock %}

templates/df_user/user_center_info.html
{% extends 'base2.html' %}
{% block content %}


    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'info' %}" class="active">· 个人信息</a></li>
                <li><a href="/order">· 全部订单</a></li>
                <li><a href="{% url 'site' %}">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>
                <ul class="user_info_list">
                    <li><span>用户名：</span>{{ user_addr.user.uname }}</li>
                    <li><span>联系方式：</span>{{ user_addr.uphone }}</li>
                    <li><span>联系地址：</span>{{ user_addr.uaddress }}</li>
                </ul>
            </div>

            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">


                    {% for g in goods %}

                        <li>
                            <a href="/{{ g.id }}"><img src="/static/images/{{ g.gpic }}"></a>
                            <h4><a href="/{{ g.id }}">{{ g.gtitle }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ g.gprice }}</span>
                                <span class="unit">{{ g.gprice }}/{{ g.gunit }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>

                    {% endfor %}


                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/df_user/user_center_order.html
{% extends 'base2.html' %}

{% block content %}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'info' %}">· 个人信息</a></li>
				<li><a href="/user/center/" class="active">· 全部订单</a></li>
				<li><a href="{% url 'site' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				<!--属性object_list：返回当前页对象的列表。-->
			{% for order in page.object_list%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odate}}</li>
					<li class="col02">订单号：{{order.oid}}</li>
					<li class="col02 stress">{{order.oIsPay}}</li>
				</ul>
				<table class="order_list_table w980">
					<tbody>
						<tr>
							<form action="/order/">

							<td width="60%">
								{% for ord_g in order.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">
									<input type="hidden" name="o_gid" value="{{ ord_g.id }}">
									<li class="col01"><img src=/static/images/{{ord_g.goods.gpic}}></li>
									<li class="col02">{{ord_g.goods.gtitle}}<em>{{ord_g.goods.gprice}}元/{{ord_g.goods.guint}}</em></li>
									<li class="col03">{{ord_g.count}}</li>
									<li class="col04"></li>
								</ul>
								{% endfor %}
							</td>
							<td width="10%" class="col07">{{order.ototal}}</td>
							{% if order.oIsPay %}
							<td width="30%">已支付</td>
							{% else%}
							<td width="15%">未支付</td>
							<td width="15%"><a href="javascript:;" class="oper_btn"><input type="submit" value="去结算"></a></td>
							{%endif%}

						</form>

						</tr>
					</tbody>
				</table>
			{% endfor %}
			<div class="pagenation">
				{% if page.has_previous %}
					<a href="?page={{ page.previous_page_number }}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
					</a>
				{% else %}
					<a><span aria-hidden="true">&laquo;</span></a>
				{% endif %}
				{% for i in page_range %}
					{% if i == page.number %}
					<a class="active"><span>{{ i }}</span></a>
					{% else %}
						{% if i == '...' %}
							<a><span>...</span></a>
						{% else %}
							<a href="?page={{ i }}">{{ i }}</a>
						{% endif %}
					{% endif %}
				{% endfor %}
				{% if page.has_next %}
					<a href="?page={{ page.next_page_number }}" aria-label="Next">
						<span aria-hidden="true">&raquo;</span>
					</a>
				{% else %}
					<a><span aria-hidden="true">&raquo;</span></a>
				{% endif %}
			</div>

		</div>
	</div>
<script>
	function total() {
		let total_all = 0, total_count = 0, total_checked = 0;
		$('.order_goods_list').each(function () {
			let price = parseFloat($(this).children('.col05').html()); //价格
			let count = parseInt($(this).find('.num_show').val());//数量
			let small_total = price * count; //小计
			console.log(price,count,small_total)
			if ($(this).children('.col01').children('input').prop('checked')) {
				//如果选中
				total_all += small_total;
				total_checked++;
			}
			total_count++;
			$(this).children('.col07').html(small_total.toFixed(2) + '元');//每一个购物车的小计
		})
		$('.settlements .col03 em').html(total_all.toFixed(2));//总价
		$('.settlements .col03 b').html(total_checked);//选中的购物车数量
		$('.total_count em').html(total_count);//一共多少商品
	}
	$(function(){
		total();

	})
</script>
{% endblock %}

templates/df_user/user_center_site.html
{% extends 'base2.html' %}
{% block content %}



    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{% url 'info' %}">· 个人信息</a></li>
                <li><a href="/order">· 全部订单</a></li>
                <li><a href="{% url 'site' %}" class="active">· 收货地址</a></li>
            </ul>
        </div>
        <div class="right_content clearfix">
            <h3 class="common_title2">收货地址</h3>
            <div class="site_con">
                <dl>
                    <dt>当前地址：</dt>
                    <dd>{{ str1 }}</dd>
                </dl>
            </div>
            <h3 class="common_title2">编辑地址</h3>
            <div class="site_con">
                <form action="/user/shou_save/" method="post">
                    {% csrf_token %}
                    <div class="form_group">
                        <label>收件人：</label>
                        <input type="text" name="shou">
                    </div>
                    <div class="form_group form_group2">
                        <label>详细地址：</label>
                        <textarea class="site_area" name="addr"></textarea>
                    </div>
                    <div class="form_group">
                        <label>邮编：</label>
                        <input type="text" name="ucode">
                    </div>
                    <div class="form_group">
                        <label>手机：</label>
                        <input type="text" name="uphone">
                    </div>
                    <input type="submit" name="" value="提交" class="info_submit">
                </form>
            </div>
        </div>
    </div>

{% endblock %}